services:
  todo-api-service:
    build:
      context: ./backend
    environment:
      - STORAGE=mysql
      - MYSQL_HOST=db
      - MYSQL_USER
      - MYSQL_PWD
      - MYSQL_DB=list
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - backend
      - frontend

  frontend:
    build:
      context: ./frontend
    labels:
      - "traefik.http.routers.my-app.rule=Host(`s148424.tech`)"
      - "traefik.http.routers.my-app.tls=true"
      - "traefik.http.routers.my-app.tls.certresolver=letsencrypt"
      - "traefik.docker.network=traefik"
    networks:
      - frontend
      - proxy

  db:
    image: mysql:8.0.29-debian
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PWD}
      - MYSQL_USER
      - MYSQL_PASSWORD=${MYSQL_PWD}
      - MYSQL_DATABASE=list
    volumes:
      - db_volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
networks:
  frontend:
  backend:
  proxy:
    external: true
    name: traefik

volumes:
  db_volume:
